name: Build and lint RaceResults frontend

on:
  pull_request:
    branches:
      - main
    paths:
      - "api/**"
      - ".github/workflows/backendDeploy.yaml"
      - ".github/workflows/backendCI.yaml"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: build
        run: dotnet build ./src/RaceResults.sln
      - name: test API
        run: dotnet test ./tests/API/Tests/Internal.Api.Tests.csproj
