name: RaceResults Dev CI

on:
  workflow_dispatch:
  push:
    branches:
      - dev
    paths:
      - "client/**"
      - ".github/workflows/frontendDevCI.yaml"
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - dev
    paths:
      - "client/**"
      - ".github/workflows/frontendDevCI.yaml"

jobs:
  Lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - name: Install packages
        run: npm install
      - name: Run eslint
        run: npm run lint

  build-and-deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2

      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_DEV_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_build_commad: "npm run stage"
          app_location: "/client"
          output_location: "/build"
