name: Build and lint RaceResults frontend

on:
  pull_request:
    branches:
      - main
    paths:
      - "client/**"
      - ".github/workflows/frontendDeploy.yaml"
      - ".github/workflows/frontendCI.yaml"

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - name: Install packages
        run: |
          npm install
      - name: run eslint
        run: npm run lint
      - name: build frontend
        run: npm run build
